### ISSUE TITLE
Bug: Tree view not consistent with how data is displayed

### ISSUE THREAD

**Issue by wtfacoconut** [fortify/fcli#104]
Currently there are two issues with the tree view:

1. In some instances, the tree view will show no data unless you explicitly specify a column/field to be displayed using the `--fields` option.
2. In some cases, like with an array of strings, elements of that array get displayed as a single line of comma separated values. 

For examples of the above, please see the two screenshots below:

![image](https://user-images.githubusercontent.com/5297545/191287487-b69969b0-243f-4163-b4ac-d057db162f29.png)
![image](https://user-images.githubusercontent.com/5297545/191287605-cbe080fe-857c-4fab-83f2-7ce3d736fd79.png)

**Comment by rsenden** [comment]
@wtfacoconut Any chance you can have a look at this?
