### ISSUE TITLE
fcli ssc session login : expiration status is unknown IF login session was created using token (-t )

### ISSUE THREAD

**Issue by james-du1** [fortify/fcli#167]
fcli ssc session login : expiration status is unknown IF login session was created using token (-t )

![image](https://user-images.githubusercontent.com/120057653/206296118-24def4f3-26fb-461d-9ca9-8a35178270ca.png)

**Comment by rsenden** [comment]
As far as I know, SSC doesn't provide functionality for retrieving token expiration date for an existing token, so fcli can't know when the token will expire, and therefore can't display whether the token has expired or not. If you know of any way for getting the token expiration date from SSC, we'll be more than happy to add this functionality to fcli. Note that all SSC token endpoints require user credentials to be provided, so we cannot call these endpoints if you're logging in with a pre-generated token.

**Comment by rsenden** [comment]
Closing this issue, as it cannot be resolved without SSC changes

**Comment by rsenden** [comment]
Fixed by c2e66bceb34ca1c3f9989dd2c63546ff0c010d99
