### ISSUE TITLE
fcli ssc app delete : need the ability to differentiate application name with only numerical numbers and application IDs

### ISSUE THREAD

**Issue by james-du1** [fortify/fcli#170]
fcli ssc app delete : need the ability to differentiate application name with only numerical numbers and application IDs

fcli ssc app delete treats all numerical numbers as application IDs but customers might have application name using only numbers

![image](https://user-images.githubusercontent.com/120057653/206307983-fa858ed9-43f0-4f5d-9df2-bc2d76930182.png)

**Comment by rsenden** [comment]
We'll need to think about a generic approach for handling numeric names versus id's, for example by having separate command line options that can be used instead of the positional parameter (i.e. `--app-id` and `--app-name`), or by using some prefix like `id:8` or `name:008`.

**Comment by wtfacoconut** [comment]
@rsenden, I'm in favor of using `--app-id` as a boolean option to indicate that an ID is being provided. If `--app-id` isn't provided, the default behavior should be to treat the positional parameter as a name. 
I think the prefix approach is a bit too unique.
