### ISSUE TITLE
fcli ssc appversion-artifact : -q should accept normal date format

### ISSUE THREAD

**Issue by james-du1** [fortify/fcli#172]
user has to input date format like 2022-06-28T20:19:35.000+00:00 which is not very user friendly
can we make it accept date format like 2022-06-28 OR 2022/06/28 ?

for example:
![image](https://user-images.githubusercontent.com/120057653/206546096-6eb01ca9-e8fc-4256-910b-ac5fe22c7b76.png)

**Comment by rsenden** [comment]
For now, the `-q` option only supports exact equals operations, i.e. you'd need to provide the full date/timestamp. Obviously this is not very user-friendly/useful; we should have the ability to match any timestamp on a given date, and even better, provide options to filter before/after a particular date. This is something that we'll look at for a future fcli version.
