### ISSUE TITLE
fcli ssc appversion-artifact download -> without sources downloads with sources 

### ISSUE THREAD

**Issue by xakrurychle** [fortify/fcli#206]
case 1
fcli ssc appversion-artifact download --appversion app:version --no-include-sources -f path --session session --id id

works as expected, file is without sources

case 2
fcli ssc appversion-artifact download --appversion app:version --include-sources -f path --session session --id id

works as expected, file is with sources

case 3

fcli ssc appversion-artifact download --appversion app:version -f path --session session --id id

documentation says no sources is enabled by default if no option is specified
https://fortify-ps.github.io/fcli/v1.0.0/fcli-ssc-appversion-artifact-download.html
 the file is, however, downloaded with sources

in my case the file size downloaded was 442 and 446 and when double-checked using UI downloads, it confirmed it.

**Comment by rsenden** [comment]
Actually, the default is to include sources. I'll update the description for this option and some similar `--[no-]...` options on other commands to better describe the default behavior.
