### ISSUE TITLE
FoD: Add Integration test script

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#226]
Add a new fod-integration-test.sh test script similar to the exists ssc-integration-test.sh script. It should include creating/deleting an application and release as well as starting a basic SAST scan. As such it will depend on the implementation of #225 .

**Comment by rsenden** [comment]
Although the `ssc-integration-test.sh` script is quite handy for doing some basic testing, it can use some improvements. For example, it would be nice if it was better modularized and would allow for running tests for a single entity/operation only. Just keep this in mind when developing a similar script for FoD.

**Comment by rsenden** [comment]
@kadraman, @rohitbaryha1 We should close this issue once Rohit's integration test script has been merged.

**Comment by kadraman** [comment]
Closed as integration script has been merged in.
