### ISSUE TITLE
FoD: Allow vulnerabilities to be retrieved for a specific application release

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#243]
Given an existing application release with scan results, create a command that allows vulnerability details to be retrieved.

For example:

`fcli fod release vulns -Filters "severityString:Critical|High"`

Note: the above uses the API filter directly, maybe we should include some default queryable options and add to the filter, e.g. [--severity Critical --severity High]

**Comment by rsenden** [comment]
Potential overlap with #85, although we may want to support both approaches.

**Comment by rsenden** [comment]
This has been implemented as `fcli fod issue list`.
