### ISSUE TITLE
FoD: Mobile application scanning - phase 1

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#260]
Add commands to work with Mobile applications, similar to the static and dynamic scans, e.g.:

`fcli fod mobile-scan start | cancel | get | list | import | wait-for`

Note: mobile scans are binary scan and can be fully automated if no manual audit/test is required.

**Comment by kadraman** [comment]
Propsoed to add `fcli fod scan start-mobile` for automated binary scanning. Setup of mobile scan (like dast) will come in additional issue

**Comment by rsenden** [comment]
@kadraman Is this still an issue, or can this be closed?

**Comment by rsenden** [comment]
Most commands for managing mobile scans are already available, other commands like setting up a mobile scan cannot be implemented until appropriate FoD endpoints become available, but as mentioned above, this should be documented in a separate issue.
