### ISSUE TITLE
FoD: Refactor Application creation command(s)

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#266]
Currently there is a single `fcli fod app create` command with many arguments for different types of applications, e.g. Web, Mobile, Microservices. It would be better for the user if we had individual creation commands for each of them. The following are proposed:

`fcli fod app create-web-app ...`
`fcli fod app create-mobile-app ...`
`fcli fod app create-microservice-app ...`

This will do away with the need for the `type` option as well as make the `microservice` options specific to the `create-microservice-app` command.

**Comment by rsenden** [comment]
This has been implemented, so this issue can be closed. Note though that this discussion has been revived in #367.
