### ISSUE TITLE
`fcli scm github-contributor list`: Personal account are not accepted as organization name

### ISSUE THREAD

**Issue by mauriziodistefano** [fortify/fcli#273]
See attached "error command" file.

![Capture](https://user-images.githubusercontent.com/53040484/228825849-acfbd3ee-fe11-436f-b86b-c06847bce32d.JPG)

**Comment by rsenden** [comment]
No longer relevant as the `fcli scm` commands have been replaced by `fcli util ncd-report`; consider raising a new issue if this functionality should be supported by the new `ncd-report` command.
