### ISSUE TITLE
FoD: `fcli fod app update` remove microservices CRUD

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#282]
It’s somewhat confusing that microservices can be created through both ‘fcli fod app update’ and ‘fcli fod app-ms create’ commands, but releases can only be created through the ‘fcli fod release create’ command. For consistency, I think ‘<entity> update’ commands should only be used to update properties of that entity, not for adding/removing/renaming sub-entities as we’d have ‘<subentity> create/delete/update’ commands for that. Of course, it would be good if the ‘app update’ command description would mention that releases and microservices can be managed through the app-ms/release commands.

Remove microservice options from `fcli fod app update` command and add reference in `fcli fod app-ms` commands in description

**Comment by rsenden** [comment]
Related to #367?

**Comment by kadraman** [comment]
Implemented
