### ISSUE TITLE
FoD:  `fcli fod scan sast-scan`  'N/A' columns

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#285]
The ' fod scan start-sast` command outputs a lot of columns containing `N/A`; is data to be expected in these columns, or should we remove them from the output?

**Comment by rsenden** [comment]
Fixed by [4de3a53](https://github.com/kadraman/fcli/commit/4de3a53f3ae8128404f9a1080d68b131e084dada)

**Comment by kadraman** [comment]
Implemented in above commit to develop branch.
