### ISSUE TITLE
`fcli util ncd-report`: GitLab Group ID needs to be used instead of Group Name

### ISSUE THREAD

**Issue by wtfacoconut** [fortify/fcli#296]
fcli version: `fcli version 0.20230505.122628-dev_2.0.0-beta, built on 2023-05-05 12:26:58`

## Issue:
When trying to then generate the report using a group name applied to the GitLab's `group.name` attribute, the `ncd-report generate` function will produce the following error in the `report-errors.csv` file: 
![image](https://user-images.githubusercontent.com/5297545/236712438-8b19be50-0ac1-47c0-b833-ee7a4003e696.png)

The resulting 404 error is because the API does not accept the Group Name, but instead requires the Group ID to be provided.

As an example, this screenshot of my config below **_does not_** work, when a Group Name is provided:
![image](https://user-images.githubusercontent.com/5297545/236712856-2bfb2054-d73f-4849-b869-3ce74eeeaf9f.png)

But using this group's Group ID **_does_** work:
![image](https://user-images.githubusercontent.com/5297545/236712810-36bcee39-aad2-426f-aac1-aae4676a3f43.png)

## Possible Solutions:
1. Either rename the `groups.name` attribute to `groups.id`
2. Or update fcli to resolve the Group ID from the provided Groun Name

## References:
- https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects

**Comment by wtfacoconut** [comment]
On further investivation with @rsenden , it was discovered that you can use either the numerical ID or the ID/Path that's present in url bar of your browser. When referencing sub-groups or nested sub-groups, you'll you can use the full path from top-level patent group to the nested sub-group:
![image](https://user-images.githubusercontent.com/5297545/236777028-0fc8e161-ce39-4382-b189-17bc8620211a.png)

**Comment by rsenden** [comment]
Closed by 5e8657e
