### ISSUE TITLE
fcli-integration-test framework - Use relative path in integration test demo data

### ISSUE THREAD

**Issue by rohitbaryha1** [fortify/fcli#302]
Do not use the exact path in the parameters

Reference: integration-test/data/FoD/fod-integation-test-data.json
"commands": "fod scan start-sast",
    "arguments": "--entitlement-id=393 --notes='notes for test cases' --file=**'C:\\Users\\RohKumar\\Downloads\\package.zip**' --entitlement-preference=SubscriptionFirstThenSingleScan --remediation-preference=NonRemediationScanOnly --in-progress-action=Queue INT_T_App1:INT_T_App1_Release1"

**Comment by rsenden** [comment]
Superseeded by https://github.com/fortify/fcli/issues/370
