### ISSUE TITLE
fcli-integration-test framework - add sample source code zip file

### ISSUE THREAD

**Issue by rohitbaryha1** [fortify/fcli#303]
Include sample source code zip file to initiate SAST scan, similar to Eightballs etc..

Reference :
commands": "fod scan start-sast",
    "arguments": "--entitlement-id=393 --notes='notes for test cases' --file='**C:\\Users\\RohKumar\\Downloads\\package.zip**'

**Comment by rsenden** [comment]
Superseeded by #370
