### ISSUE TITLE
fcli-integration-test framework - Use Scan ID as output varibale to wait for the scan to finish

### ISSUE THREAD

**Issue by rohitbaryha1** [fortify/fcli#314]
Kevin Comment:
Its probably possible to retrieve scan id for imported scan and then use it in `fod scan get XXX` but it might be safer to have one existing setup release (see below)
If we have one existing app/release setup can you make it configurable, either via environment variable or template.
Maybe even skip the test if the release is not found?

**Comment by rsenden** [comment]
Superseded by https://github.com/fortify/fcli/issues/370
