### ISSUE TITLE
Merge changes on `main` onto `develop`

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#317]
The `main` branch contains some fixes/features that are not available in the `develop` branch yet; should we merge these into `develop` to allow for QA testing of the combined changes, or should we just merge `develop` onto `main` once we're ready for the 2.0.0 release?

**Comment by wtfacoconut** [comment]
@rsenden is there any concerns or risks if we merge in the changes/fixes from main to development?

**Comment by rsenden** [comment]
@wtfacoconut not sure whether this would cause issues when merging `develop` onto `main`, but I guess we'd just get a merge commit when merging `main` onto `develop` and then another merge commit when merging `develop` back onto `main`?

**Comment by rsenden** [comment]
Done
