### ISSUE TITLE
FoD: Refactor argument options to lowercase

### ISSUE THREAD

**Issue by kadraman** [fortify/fcli#329]
For consistency with other modules any FoD argument options should be changed to lowercase.
For example:

`fod app create-microservice-app --criticality=High --status=Development --owner=kevin.lee --microservices=ms1,ms2,ms3 --release-microservice=ms2 --auto-required-attrs fcli-test-a:1.0`

should be changed to allow:

`fod app create-microservice-app --criticality=high --status=development --owner=kevin.lee --microservices=ms1,ms2,ms3 --release-microservice=ms2 --auto-required-attrs fcli-test-a:1.0`

I believe the API is case insensitive but all commands will need to be tested and test scripts updated.

**Comment by kadraman** [comment]
Yes, agreed but see below...

With your example, to get it to work in FoD you would actually need to do:

`fcli fod app list -q "businessCriticalityType=='High'"`

(powershell you need to swap single and double quotes)

even more confusing to query on the type, if you wanted to see web apps you would need to use the internal value:

`fcli fod app list -q "applicationType=='Web_Thick_Client'"`

As you know all the `-q` options can be found using `-o json-properties` but it does require knowledge of the FoD API to really understand what the values are.

Parking this one until we can or cannot come up with a better way.

**Comment by rsenden** [comment]
Potentially we could use record transformers to transform both property names and values, for example transform `"applicationType": "Web_Thick_Client"` to `"type": "web"`. This would allow users to do `fcli fod app list -q 'type=="web"'`.

However:
* This might be a lot of effort
* We'll need to be able to do the reverse transformation as well, in case client-side queries get converted into server-side queries; we can already do this for property names but not property values
* This may cause issues if FoD ever adds new properties that conflict with our renamed properties (for example, renaming `applicationType` to `type` would cause problems if FoD ever introduces a new `type` property)
* This will cause a lot of confusion for people familiar with the FoD REST API

**Comment by rsenden** [comment]
After closer inspection, this will likely require too much work to implement and maintain, and may reduce user experience due to inconsistencies with query/output expressions, so most likely we'll just stick to whatever format is used by the target system.

**Comment by rsenden** [comment]
Closing this issue, as we've long made the decision to stick to whatever format is used by the target system.
