### ISSUE TITLE
General documentation typos, remarks

### ISSUE THREAD

**Issue by xakrurychle** [fortify/fcli#333]
![image](https://github.com/fortify/fcli/assets/63144637/7fd1a9ae-b0c6-4e00-823a-550965b77a95)
https://fortify.github.io/fcli/dev_2.0.0-beta/#_fcli_data_folder
The locations of these files can be **controller** through the following environment variables:
-> **controlled**

![image](https://github.com/fortify/fcli/assets/63144637/f7c14456-dc4d-407d-9878-c55f91371527)
https://fortify.github.io/fcli/dev_2.0.0-beta/#_installation
If you experience any unexpected behavior with native binaries, like commands or command line options not being listed or recognized, or technical error messages about methods, constructors or serializers not being found, please try with the Java version **a s** it may be an issue specific to the native binaries. See the [Troubleshooting](https://fortify.github.io/fcli/dev_2.0.0-beta/#_troubleshooting) section for details.
-> **as**

![image](https://github.com/fortify/fcli/assets/63144637/3cd7b422-80fb-4492-a5b6-9be1bc3caa06)
https://fortify.github.io/fcli/dev_2.0.0-beta/#_fcli_variables
![image](https://github.com/fortify/fcli/assets/63144637/1adaab32-6718-46a2-8439-daa1f812a6bd)

![image](https://github.com/fortify/fcli/assets/63144637/5e141629-5ddf-4837-9d0d-57b225904429)
https://fortify.github.io/fcli/dev_2.0.0-beta/#_store
-> missing gap in " --store " option

**Comment by rsenden** [comment]
@xakrurychle Thanks for reporting, we'll look into fixing these typos
