### ISSUE TITLE
Missing possibility to refresh AV metrics

### ISSUE THREAD

**Issue by xakrurychle** [fortify/fcli#335]
Missing possibility to refresh metrics after updating for example issue template.

Scenario:

User updates AV's issue template, in SSC that actions prompts user to 'refresh' the application's metrics. I failed to find a command to do so in fcli.

**Comment by rsenden** [comment]
@xakrurychle Indeed, this would be good functionality to have in fcli. I guess we could have an `fcli ssc appversion refresh` command, or do you have any other suggestions as where this functionality should live in fcli?

Whether an application version needs to be refreshed is already visible in the output of `./fcli ssc appversion list -o json` for example, but not visible in the default fcli output. Maybe we should look into adding this to the default table output as well if there's enough space; potentially we can just add a column displaying `*` if refresh is required (or potentially, we could display `*` if any attention is required, like refresh required, artifacts requiring approval, ..., although this may require additional endpoints to be queried and thus affect performance)

Also note that users can already use fcli query functionality to list only application versions for which refresh is (not) required; we should add these sample queries to #318:
![image](https://github.com/fortify/fcli/assets/8635138/3edea2fe-ae65-4146-a4d2-ba0662e632c3)

**Comment by xakrurychle** [comment]
> @xakrurychle Indeed, this would be good functionality to have in fcli. I guess we could have an `fcli ssc appversion refresh` command, or do you have any other suggestions as where this functionality should live in fcli?
> 

I believe `fcli ssc appversion refresh` is enough, any change that requires refresh is always within the application itself.
