### ISSUE TITLE
unable to use ~/ as path to file

### ISSUE THREAD

**Issue by xakrurychle** [fortify/fcli#336]
fcli ssc appversion-artifact upload ~/here.fpr --appversion ::myFCLICreatedVersion:: 
Autocompletion for the upload option does not work with ~/xyz but works with /home/user/xyz

**Comment by rsenden** [comment]
The auto-completion script is generated by the CLI framework that we're using, so we don't have direct control over the contents. We'd need to wait for a patch (or contribute a patch ourselves).

@wtfacoconut Can you please confirm this issue, and then report this on the picocli issues page? Of course, if you can develop a patch, that would be even better.

**Comment by wtfacoconut** [comment]
> fcli ssc appversion-artifact upload ~/here.fpr --appversion ::myFCLICreatedVersion:: Autocompletion for the upload option does not work with ~/xyz but works with /home/user/xyz

Hey @xakrurychle , it's somewhat clear that you're doing this from some kind of *nix shell. Can you detail which OS and shell you're running fcli from?

**Comment by xakrurychle** [comment]
> > fcli ssc appversion-artifact upload ~/here.fpr --appversion ::myFCLICreatedVersion:: Autocompletion for the upload option does not work with ~/xyz but works with /home/user/xyz
> 
> Hey @xakrurychle , it's somewhat clear that you're doing this from some kind of *nix shell. Can you detail which OS and shell you're running fcli from?

$ $SHELL --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


> Also, when you say "autocompletion", are you saying that you're running the command `fcli ssc appversion-artifact upload ~/here.fpr --appversion ::myFCLICreatedVersion::` and fcli is simply throwing an exception because the full absolute path to the fpr file wasn't provided? Or are you saying that you tried to double-tap the `<tab>` key on `~/here.fpr` where by your expecting for the shell to then fully expand that parameter to a full path?

What I mean by autocompletion is the latter you mention. Using `~/` won't allow me to use `<tab>` to finish the path, using full-scalled `/home/.../.../` allowed for `<tab>` completion.

**Comment by rsenden** [comment]
Being a Java application, fcli doesn't support `~` to represent a home directory out of the box, hence the auto-completion script doesn't recognize this either. If you try passing `~/some/path` to an fcli option taking a path/file, fcli will fail with an error indicating that the path cannot be found.

Potentially we could manually implement `~` support for every fcli option that takes a file/path as input. Not sure though whether we can implement this in a generic way; potentially we'd need to have custom logic in every applicable fcli command, thereby making it difficult to provide and maintain consistency between the different commands.

If we choose to implement support for `~`, it remains to be seen whether the auto-completion script can also be tailored to support this. Also, we'd only be able to support a plain `~` to represent the home directory of the current user; expanding `~otherUser` is a shell feature which cannot be implemented in a cross-platform way.

**Comment by xakrurychle** [comment]
The reason for raising this is because I use fortifyclient on daily basis and using FCLI as a successor with extended options and possibilities, the absence of tabbing feature for `~/` path became visible basically immediatelly.

**Comment by rsenden** [comment]
Further research shows that this issue only affects positional parameters; completion candidates are correctly shown when `~/` is used on options (as long as these are declared to take `File` or `Path` instances; see #351)
