### ISSUE TITLE
fcli ssc rest call --data help incorrect

### ISSUE THREAD

**Issue by jcox10** [fortify/fcli#342]
The help for `fcli ssc rest call --data` incorrectly says it is a path to a file: `This option will read data from a file for your request.` Per [this line](https://github.com/fortify/fcli/blob/develop/fcli-common/src/main/java/com/fortify/cli/common/rest/cli/cmd/AbstractRestCallCommand.java#L40) it is not yet implemented.

The help text should indicate that data is a STRING value, not a file.

**Comment by rsenden** [comment]
@jcox10 Thanks for reporting this, we'll have a look at fixing this with the next fcli release.
