### ISSUE TITLE
fcli -  list commands enhancement

### ISSUE THREAD

**Issue by xakrurychle** [fortify/fcli#343]
I'd call this enhancement.
Scenario:
The issue I encountered is as follows.
For some reason I needed to create over 90K application versions in one ssc instance. Lets say a company really does carry that many of them but any number in higher couple of hundreds is a lot... Can we add some limit to the list command so that users can specify how many versions to list and see?

./fcli ssc appversion list | ls  `--newOption <number of AV to list at once and then some mechanism to list another increment etc>`

**Comment by xakrurychle** [comment]
So to add to it, similar issue arose when trying to run `fcli ssc activity-feed ls`. Once customers reach higher numbers of app versions or their instances will rarely be restarted or redeployed, I am afraid there is risky potential for the list commands to encounter hundreds or thousands or records and all of them will be printed to stdout at once. The `list | ls` options throughout the tool should offer a generic way to list only a portion of these records with some additional incremental value.

**Comment by rsenden** [comment]
Closing as duplicate of #120
