### ISSUE TITLE
Move `ncd-report` and `msp-report` commands

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#358]
We currently have `fcli util ncd-report *` and `fcli util msp-report *` commands. However, these license reporting commands don't fit very well alongside the other commands in the `fcli util` module, as these other commands are low-level utility commands.

The idea is to move these commands to a new `report` module, resulting in the following command structure:

* `fcli report msp-license generate-config`
* `fcli report msp-license generate`
* `fcli report ncd-license generate-config`
* `fcli report ncd-license generate`

Moving these commands to a dedicated module seems to be more appropriate, and gives us a good place to add more reporting commands. 

Any reporting functionality provided by Fortify products will be covered in the respective product modules though, like `fcli ssc report generate`). As such, it's not clear yet whether there will be any more 'fcli-native' reports, in which case it may be overkill to introduce a new `report` module with just two sub-commands.

Ideas/suggestions/...?

**Comment by psmf22** [comment]
I´d leave them in util unless there are plans to introduce more of these, a top level report command might lead to confusion with the product reports

**Comment by rsenden** [comment]
According to internal email conversation, there will likely be more license-related reports; so far there seem to be no plans for similar reports that are not related to licensing.

So, instead of having a generic `report` module, which as mentioned may cause some confusion (also because `report` is both a verb and entity), maybe we should instead have a dedicated `license` or `licensing` module?

```
fcli license msp-report ...
fcli licensing msp-report ...
```

Any preference for one of these, or alternative suggestions?
