### ISSUE TITLE
Fix FoD command usage headers

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#359]
As per fcli convention, command usage headers should provide a one-line summary; any remaining information that may be useful for the user should go into the usage description. As shown in the screenshot below, some FoD commands have a much longer usage header; this should be fixed.

![image](https://github.com/fortify/fcli/assets/8635138/55b07828-1475-4983-b162-3b8f6de443d2)

**Comment by kadraman** [comment]
Yep, I didn't release this - just based the properties file on the ssc one as it existed a while ago and missed this communication :)
Will update it.
