### ISSUE TITLE
SSC: Implement commands and mixin "groupBy" groups

### ISSUE THREAD

**Issue by wtfacoconut** [fortify/fcli#432]
For commands like `fcli ssc issue count`, it has an option called `--by` which allows the user to change which criteria to group issues by. Currently, this option only accepts a guid.
It might be a good idea to create a command for retrieving groupings available for a specified application version as it's cumbersome for the user to manually query the API for this information.

**Comment by rsenden** [comment]
Closing this issue, as the `fcli ssc issue count` command now allows for specifying either group name or id (and the same for filters), and commands have been added to list available groups & filters.
