### ISSUE TITLE
SSC: Implement 'ssc user create' command(s)

### ISSUE THREAD

**Issue by wtfacoconut** [fortify/fcli#45]
- List and delete commands already available
- Single command for both local and LDAP users, or separate commands?

**Comment by rsenden** [comment]
We don't need to cover every possible SSC API in v1.0, and I see this as lesser priority than some other tasks, so I'd like to suggest moving this to a later milestone.

**Comment by wtfacoconut** [comment]
I've moved this issue to the v1.1 milestone, but I do believe that we should still at lease have some basic commands for local user management.

Maybe I close this issue and create separate issues for local, LDAP, and SSO user management?

**Comment by rsenden** [comment]
Reason why I stated there are more important tasks to focus on is that I think we should focus first on functionality for end users, like enabling pipeline integrations. Administrative tasks like user management are also important, but can be postponed to a later version.

As for creating separate issues; I think there is already an issue for LDAP user management, which may or may not overlap with this issue depending on whether we put all user types under the `user` command, or have separate entities for local, LDAP and SSO user management. 

This requires more detailed analysis of how the SSC API endpoints are structured. For example, the current `user list` command returns both local users and LDAP entities, but we may need to have separate `create` and `update` commands for local vs LDAP users, in which case it would be better to have for example `ldap-entity create/list/update/delete` and `local-user create/list/update/delete` commands.

**Comment by rsenden** [comment]
There are already commands for managing users under `fcli ssc access-control`, including a `create-local-user` command. Managing LDAP entities is discussed in #46, so this issue can be closed.
