### ISSUE TITLE
`limit` option for FoD and SSC action reports

### ISSUE THREAD

**Issue by wtfacoconut** [fortify/fcli#523]
Currently FoD actions will retrieve 50 issues at a time and SSC will retrieve 100 issues at a time. 
It might be a good idea to expose an action option so that users can adjust this value for performance reasons.

**Comment by rsenden** [comment]
For SSC, a `--page-size` option has now been added. We won't do this for FoD for now for two reasons:

- Maximum page size is configured at tenant level; we don't want to risk running into errors if users set the value higher than tenant maximum.
- Rate limits on issue details endpoints likely have a much bigger impact on performance than page size.
