### ISSUE TITLE
java -jar fcli.jar sc-sast scan wait-for --help

### ISSUE THREAD

**Issue by dgarozzo** [fortify/fcli#529]
What would be the correct set of options to use for fcli sc-sast scan wait-for if I wanted to wait for a scan to be completely finished, uploaded and completely merged in with existing scan results? I'm not sure which to wait for, and I'm concerned about what might happen if I were to wait for something like ANALYSIS_COMPLETE but then the state changed to something like ERROR_PROCESSING, or CANCELED, or FAULTED and it would never actually get to ANALYSIS_COMPLETE - would it wait indefinitely? Do I need to specify all terminal end points in my wait-for list?

**Comment by rsenden** [comment]
Sorry for the delayed reply, overlooked this question. In general, there should be no need to explicitly list any states; default values should work just fine in most cases. In general, fcli wait-for commands differentiate between 'in progress', 'completed' and 'error' states, and by default the command will throw an error if any error state like `ERROR_PROCESSING` is detected. Note that this is somewhat dependent on SSC/ScanCentral SAST version as detailed in the wait-for command help.
