### ISSUE TITLE
RE: Unknown option "--appversion"

### ISSUE THREAD

**Issue by patrickpannn** [fortify/fcli#550]
### Question

Hi, I am trying to run`fcli sc-sast scan start --appversion 1 -p ...`, it failed with "Unknown option --appversion" for fcli 2.4.0. It was working for 1.2.3. Can someone please shed some lights on this? Thanks

**Comment by rsenden** [comment]
Hi Patrick, 

For fcli 2.x.y, the command-line option to use for specifying the application version is `--publish-to`, to better describe the action taken by this option, and for consistency with the SSC ScanCentral DAST UI, which has a dedicated 'publish' button.

As per semantic versioning conventions, we try to maintain backward compatibility within a single major version range, i.e., between fcli versions 1.0.0 and 1.1.0 we don't remove or rename commands and options, but potentially we can add new commands/options in 1.1.0. 

Between major fcli versions, i.e., from 1.x.y to 2.x.y, there may be 'breaking' changes like renamed or removed commands and options. This was especially the case for 2.0.0; based on feedback on the initial fcli releases, we did some major refactoring of commands and options to provide more consistency and better clarity, and to improve general user experience.

I don't foresee any such major changes in the near future (although one can never be sure of course), as users are quite happy with current command structure. If we do decide to release a new major 3.0.0 version, most likely it will only affect a small set of fcli commands, for example to remove some deprecated functionality.

**Comment by patrickpannn** [comment]
Thanks a lot. I am trying to run `fcli ssc appversion-vuln count --appversion 1 ...`, which failed. It says "Unmatched arguments from index 1". I am thinking maybe the command is changed?

**Comment by MikeTheSnowman** [comment]
Hey @patrickpannn. If you're still using fcli v2.4.0 as you mentioned in your initial message, then the command that you want to use will be:
`fcli ssc issue count --av <appVersionId> ...`
