### ISSUE TITLE
Re: Java11 scan

### ISSUE THREAD

**Issue by patrickpannn** [fortify/fcli#558]
### Question

Hi there,

I have a java11 project and was fine with running the fortify cli 1.2.3. Recently, I upgraded to 2.4.0 and then it failed. It says unsupported java runtime (class file version 61.0). I am using java17 to run the fcli.jar, but still not able to package the project. Can anyone please help? Thanks

**Comment by rsenden** [comment]
Hi @patrickpannn, can you provide more details as to what commands you're trying to run, and which command is failing exactly? Fcli can't package source code; you'd need to run ScanCentral Client for that, so is it an `fcli` or `scancentral` command that's failing?

Class file version 61.0 corresponds to Java 17, so it seems like you're trying to run the affected command with an older Java version. I think fcli 1.x required Java 11, whereas fcli 2.x requires Java 17 (or later). Similar for ScanCentral Client, earlier versions required Java 11, whereas the latest 24.2 version requires Java 17.

So, I'd start by double-checking the `PATH` and other environment variables like `JAVA_HOME` and `SCANCENTRAL_JAVA_HOME`, and maybe adding `java -version` statements to your pipeline to verify which Java version is being used by default.

**Comment by rsenden** [comment]
Hi @patrickpannn, any updates on this issue?

**Comment by rsenden** [comment]
Closing this issue for now as no update was provided by user; please re-open or create a new issue if needed.
