### ISSUE TITLE
fcli fod release update should allow to retire releases

### ISSUE THREAD

**Issue by pperez** [fortify/fcli#660]
### Enhancement Request

Hi, i was trying to do some automated cleaning of releases on some fortify app's releases, mainly trying to retire older releases, the problem is that fcli only allows to change the sdlc type of a release to production, development or qa and i want to retire some of them.
From the man page the only supported values for the sdlc status are the aforementioned (https://fortify.github.io/fcli/dev_develop/manpage/fcli-fod-release-update.html). (And the docs match the cli usage, there's no way to do it with the current command).
I tried this on 2.11.1 release of fcli.

**Comment by rsenden** [comment]
Hi @pperez, fcli 2.12.0 (https://github.com/fortify/fcli/releases/tag/v2.12.0) now supports the `Retired` option for `--sdlc-status`.

**Comment by patricioperezv** [comment]
@rsenden you guys are awesome, thanks a lot! 🍻 Happy holidays :)
