### ISSUE TITLE
DevDoc: Add developer documentation

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#68]
Add documentation for fcli developers, for example:
- Architecture description
- Use of annotations (Micronaut, picocli, ReflectiveAccess, FixInjection, OutputFilter, AddAsDefaultColumn, ...)
- Coding style (use of 4 spaces instead of tabs, ...)
- Best practices (see for example #27)
- CI/CD process, use of conventional commit messages, ...

**Comment by wtfacoconut** [comment]
Non-functional issue. Won't assign to any specific milestone, but will leave open.

**Comment by rsenden** [comment]
The most important developer documentation is now available at https://fortify.github.io/fcli/dev-info.html, but this could be further improved.

**Comment by rsenden** [comment]
Developer documentation is considered fairly complete now, so closing this issue.
