### ISSUE TITLE
SC-DAST: Review session management

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#74]
sc-dast commands currently use SSC sessions, and the 'sc-dast session' commands simply point to the SSC session commands. It may make sense to implement dedicated session management for SC-DAST:
- Consistency; other modules like sc-sast likely can't reuse SSC sessions as they need different login options, additional tokens, ...
- Can use a more long-lived CIToken instead of the UnifiedLoginToken provided by the ssc module, avoiding issues like token expiration while a long-running command is still running

**Comment by wtfacoconut** [comment]
Just to add in a note, for easier reference. According to the our DAST product manager:
```
The SC DAST global service should have its own token to process the scan. SC DAST only uses the ULT for the UI, not for the scan itself. So, they should be able to revoke the token once the scan has been started
i.e. User's ULT is not used when the scan is running or being uploaded 
```

**Comment by wtfacoconut** [comment]
Current implementation is already functional, will assign this issue to a later release.

**Comment by rsenden** [comment]
Indeed it's already functional, but this could potentially cause changes to the `sc-dast session` commands, requiring users to change their pipelines if they have already started using this functionality. So, if possible, we should try to get this in before an official v1 release.

**Comment by wtfacoconut** [comment]
> Indeed it's already functional, but this could potentially cause changes to the `sc-dast session` commands, requiring users to change their pipelines if they have already started using this functionality. So, if possible, we should try to get this in before an official v1 release.

Understood. Moving to v1.0 release milestone.

**Comment by rsenden** [comment]
Already implemented; sc-dast commands now have their own sessions separate from SSC sessions
