### ISSUE TITLE
Output: Update message bundles and resource keys

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#77]
- While implementing and refactoring commands, we haven't kept the resource bundles up to date. We should go over all commands and options to make sure that we have proper descriptions for all
- Some picocli annotations explicitly refer to message keys; we should review whether this is always necessary, and remove those explicit message keys if not needed
- In the usage message for login commands, also describe the environment variables that can be used as an alternative to the login command

**Comment by wtfacoconut** [comment]
Also at a later date, we'll want to source some help for translations once all the english messages have been established.

**Comment by rsenden** [comment]
Usage message for login commands already have environment variables listed. Resource bundles have been updated to have descriptions for all commands and options, but some descriptions can probably still be improved.

**Comment by rsenden** [comment]
Based on FortifyCLITest, we now make sure that we have proper usage headers for all commands, and that all options and positional parameters have a description. As such, this generic issue can be closed. If there are any potential improvements to be made to individual descriptions, for example based on user feedback, we'll open dedicated issues for those.
