### ISSUE TITLE
SC-SAST: Implement 'sc-sast scan prepare' command

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#81]
This should be based on the `scancentral package` command. Initially, we would require ScanCentral Client to be installed, with the 'sc-sast scan prepare' command simply being a wrapper for the `scancentral package` command. Eventually, packaging functionality should be natively integrated into fcli.

**Comment by Grisolfi** [comment]
That will be awesome to have. @rsenden

**Comment by rsenden** [comment]
Merging with #82, as implementation will be very similar.
