### ISSUE TITLE
Output: Add support for ordering results

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#86]
For endpoints that support it, we could simply pass an `orderby` request parameter to allow for server-side ordering. In the command implementation, we probably want to use enums to list the fields that are supported for the `orderby` parameter.

We could also consider client-side ordering, but that will likely negatively impact performance as we first need to load the full list of results (possibly requiring rather significant changes to `OutputMixin`), and wouldn't work if we want to support increment output (see #80).

**Comment by wtfacoconut** [comment]
For now, not assigning to a milestone. At the moment, we can just advice users to manually sort the results after they output data to a file using the sort command (linux/mac). Powershell should have an equivilent command on windows.

**Comment by rsenden** [comment]
Duplicate of #120, closing this one as #120 provides more details.
