### ISSUE TITLE
Consistency: Positional parameters vs options

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#87]
- Decide on when to use positional parameters instead of options
- Describe this decision in fcli developer documentation, including examples
- Update all relevant commands to use positional parameters where applicable

Positional parameters should only be used to specify the main target(s) of a command. In some cases, it may be necessary to use a different command name in order to have consistent behavior. Also keep in mind that even if a certain command currently only accepts a single input (option/parameter), in the future there may be a need to add additional inputs, which could result in the original choice to use a positional parameter for the single input is no longer a good choice, as it may make more sense to use positional parameters for some of the new inputs.

Some examples:
- For commands that upload files, like `ssc appversion-artifact upload`, it makes sense to use a positional parameter to take the file to be uploaded, and use options to indicate where the file should be uploaded for example
- For commands that create an entity containing a file, there are likely multiple attributes that make up that entity, of which the file to be uploaded is only one. In this case, it makes sense to use an option to specify the file name, for example in the `ssc report-template create` command 
- Most sub-entity commands use an option to specify the main entity, like the `--to <appversion>` option in the `ssc appversion-artifact upload` command. To have this consistent across commands, it may be necessary to use a different command name. Some examples:
    - `ssc appversion-attribute update`; with this command name, it would be logical to use a positional parameter for `<appversion>`, and `--attr <name>=<value>` options for the attributes to be updated, however this is not consistent with other sub-entity commands that use `--to`, `--from`, ... options to specify the appversion id/name
    - `ssc appversion-attribute set`; with this command name, it is logical to use `<name>=<value>` positional parameters for the attributes to be updated, combined with a `--for <appversion>` option, making this command consistent with other sub-entity commands
    - Similarly, consider `ssc appversion-user update <appversion> --assign <u1> --remove <u2>` versus `ssc appversion-user assign <u1> <u2> --to <appversion>` and `ssc appversion-user remove <u1> <u2> --from <appversion>`

**Comment by wtfacoconut** [comment]
My vote is to use positional parameters when possible as it will result in less options that the user needs to type while maintaining readability.

Below is my proposal. Any other input is welcomed.

In my explanation below, I'll use the following terms:
- _compound entity_: 
  - This refers to subcommands where you interact with an entities via a parent entity. 
  - For example: `fcli ssc appversion-users`. A compound entity uses the syntax of `<entity_parent>-<entity_child>`.
- _entity-parent / entity-child_ : 
  - In the context of _compound entity_, the parent refers to the entity on the left side of the hyphen character (-) in a subcommand name and the child is on the right side. 
  - For example with the command `fcli ssc appversion-users`, we have `appversion-user` as the compound entity where `appversion` is the _entity-parent_ and `user` as the _entity-child_.
- _singular entity_: 
  - This refers to subcommands where you interact with entities directly 
  - (eg: `ssc application`, `ssc appversion`, `ssc report`).

In general there are a two scenarios that I see occuring with fcli that we need to account for:
- General rules of thumb:
    - The primary entity instance should be specified as a positional parameter while all attributes or options associated with the entity should be specified by named options.
    - In cases where there are multiple singular, or child entity instances, then a multiplicity of two or more should specified for the positional parameter.
    - If there is a subcommand being invoked where there's no clear or obvious way to specify an entity instance in a positional parameter, then named options should be exclusively used.
1. Interactions with singluar entities:
    - The entity being interacted with should be specified in the first positional parameter 
    - Syntax: fcli ```<product> <entity> <verb> <entity_instance>``` (eg: `ssc appversion get webgoat:5.0`)
2. Interactions with compond entities:
    - The parent entity being interacted with should be specified in the first positional parameter while the child should be the second positional parameter
    - Syntax: fcli ```<product> <compound_entity> <verb> <parent_entity_instance> <child_entity_instance>``` (eg: `ssc appversion-user get webgoat:5.0 jsmith`)
3. Interactions with a subcommand where there's no obvious entity instance specify in a positional parameter.
    - eg: `sc-sast scan start --src mySrcCode.zip --to webgoat:5.0`

**Comment by wtfacoconut** [comment]
Also, if it's of any help, I've tried to borrow ideas from how kubectl and docker do things with their CLI.

- https://dockerlabs.collabnix.com/docker/cheatsheet/
- https://kubernetes.io/docs/reference/kubectl/cheatsheet/

**Comment by rsenden** [comment]
I think having multiple types of positional parameters (i.e. `<parent_entity_instance> <child_entity_instance>`) may cause confusion as to the order in which these need to be specified, and also doesn't look very logical; I think something like `ssc appversion-user get jsmith --from webgoat:5.0` looks much more logical than `ssc appversion-user get webgoat:5.0 jsmith`. 

Also not sure what Docker or kubectl examples you are referring to that have two types of positional parameters, the only examples I can find are `kubectl label pods` and `kubectl annotate pods` commands. But here it is somewhat more logical because they use `<verb> <entity>`, so the first positional parameter relates to `<entity>` and the remainder of the command line relates to `verb`.

**Comment by wtfacoconut** [comment]
The example that you gave (`appversion-user get jsmith --from webgoat:5.0`) is something that I can get behind. having that one named option, `--from`, isn't that much extra work for a user and I don't think it makes the fully typed out command too verbose either, which is nice.

**Comment by rsenden** [comment]
For now, the use of positional parameters versus options has been decided upon and is being consistently applied across all fcli commands. Possibly we'll revisit the decision later, but this issue can be closed for now.
