### ISSUE TITLE
Consistency: Review logging functionality

### ISSUE THREAD

**Issue by rsenden** [fortify/fcli#92]
- Currently no logging is performed unless --log-file is specified. We should consider enabling logging by default, with a default log file in ~/.fortify/fcli/logs, to be consistent with other Fortify tools.
- Hardly any fcli commands/helper classes do any kind of logging; we may want to add some debug logging. For example, we could log every command invocation at debug level, and perform debug/trace logging when any significant processing is being done.
- Some commands may produce warnings (like failure to clean up a previous session when logging in to a new session); we should log these at warning level, and configure logging to output warning/error/fatal messages to stderr

**Comment by wtfacoconut** [comment]
I'd say that this one will be quite important. assigning to the v1.0 milestone.
